openapi: 3.0.0
info:
  title: GoogleMeetTimer WEB API
  version: 1.0.0
paths:
  /heartbeat:
    get:
      summary: 死活監視用API
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HeartBeatResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /speechTextSignedUrl:
    get:
      summary: mp3ファイルの認証付きURLを取得する
      parameters:
        - name: text
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpeechTextSignedUrlResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /fetchVoice:
    put:
      summary: meetingIdの音声データを最新の状態にする
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FetchVoicePutRequest'
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FetchVoicePutResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  responses:
    Found:
      description: Found
      headers:
        Location:
          schema:
            type: string
            format: uri
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WebApiErrorResponse'
    Unauthorized:
      description: Unauthorized request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WebApiErrorResponse'
    Forbidden:
      description: Forbidden request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WebApiErrorResponse'
    NotFound:
      description: NotFound request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WebApiErrorResponse'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WebApiErrorResponse'
  schemas:
    # WebApiError
    WebApiErrorResponseMessage:
      type: object
      properties:
        type:
          type: string
          default: ""
        message:
          type: string
          default: "An error occurred"
      required:
        - type
        - message
    WebApiErrorResponse:
      type: object
      properties:
        data:
          type: object
        success:
          type: boolean
          default: false
        messages:
          type: array
          items:
              $ref: "#/components/schemas/WebApiErrorResponseMessage"

    # HeartBeat
    HeartBeatResponse:
      type: boolean
      
    # SpeechTextSignedUrl
    SpeechTextSignedUrlResponse:
      type: object
      properties:
        url:
          type: string
          description: 音声データの認証付きURL
      required:
        - url

    # FetchVoice
    FetchVoicePutRequest:
      type: object
      properties:
        meetingId:
          type: string
          description: 会議ID
        textId:
            type: string
            description: テキストID
        speakerId:
          type: number
          description: 話者ID
      required:
        - meetingId
        - textId
    FetchVoicePutResponse:
      type: object
      properties:
        success:
          type: boolean
          description: 成功したかどうか
      required:
        - success
